TRy this

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,31 +1,54 @@
 #!/usr/bin/env bash
-# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
-# The name of the custom HTTP header must be X-Served-By
-# The value of the custom HTTP header must be the hostname of the server Nginx is running on
+#configure a custom 404 page
+
 sudo apt-get update
-sudo apt-get -y install nginx
-
-# configure firewall to allow request through port 80
-sudo ufw allow 'Nginx HTTP'
-
-sudo mkdir -p /var/www/html
-
-# change permissions to allow us to easily create files in this directory
+sudo apt-get install -y nginx
+ufw allow 'Nginx HTTP'
 sudo chmod -R 755 /var/www
+echo 'Hello World' | sudo tee /var/www/html/index.html
 
-#  create the index page
-echo 'Hello World!' |sudo tee  /var/www/html/index.html
+# backup the original config file
+sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
 
-# create a webpage for error 404
-echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
 
-# code to configure redirect for a single page(/redirect_me) and add header to display hostname
-string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
-sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
+nginx_default_file="/etc/nginx/sites-available/default"
+header_name="X-Served_By"
+header_value='$hostname'
 
-# code to configure redirect for 404 error page
-string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
-sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
+if grep -q "add_header $header_name" $nginx_default_file; then
+  echo "Header already exists in Nginx default file"
+else
+  sed -i "/server {/a add_header $header_name $header_value;" $nginx_default_file
+  echo "Header added to Nginx default file"
+fi
 
-# restart the web server after updating the settings
-sudo service nginx restart
+
+# check if the redirect rule already exists
+if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
+    # add the redirect rule to the config file
+    sudo sed -i 's/location \/redirect_me {\n        rewrite ^\/redirect_me$ https:\/\/twitter.com\/jmagolo_jnr$1 permanent;\n    }\n\n\n\n/g' /etc/nginx/sites-available/default
+else
+    echo "Redirect rule already exists, no changes made."
+fi
+
+# check if the error page already exists
+if ! grep -q "error_page 404 /404.html" /etc/nginx/sites-available/default; then
+    # create the error page file
+    echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
+    # add the error page configuration to the default file
+    sudo bash -c 'echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default'
+else
+    echo "Error page already exists, no changes made."
+fi
+
+#Test config
+sudo nginx -t
+
+# reload the Nginx
+
+if ! pgrep nginx > /dev/null;
+then
+   sudo service nginx start
+else
+   sudo service nginx restart
+fi
